### ISSUE TITLE
!raid addpts causes SQL error with MySQL/MariaDB

### ISSUE THREAD

**Issue by cap5lut** [Budabot/Tyrbot#131]
When trying to add points for raiders, eg `!raid addpts tnh` (the preset doesnt matter as long as it is a valid one) an exception was thrown.

this error only occurs when using MySQL or MariaDB, it does **not** occur for SQLite.

Reproduction steps:
- use a bot that is configured for MySQL/MariaDB
- `!raid start test`
- `!raid addpts tnh`

```
testbot-mysql      | 2024-01-28 10:10:51,951 - INFO - core.tyrbot - (bot0) From Capmafroob: raid addpts tnh
testbot-mysql      | 2024-01-28 10:10:52,010 - ERROR - core.command_service - error processing command: raid addpts tnh
testbot-mysql      | Traceback (most recent call last):
testbot-mysql      |   File "/app/deps/mysql/connector/connection_cext.py", line 633, in cmd_query
testbot-mysql      |     self._cmysql.query(
testbot-mysql      | _mysql_connector.MySQLInterfaceError: Field 'log_id' doesn't have a default value
testbot-mysql      |
testbot-mysql      | The above exception was the direct cause of the following exception:
testbot-mysql      |
testbot-mysql      | Traceback (most recent call last):
testbot-mysql      |   File "/app/core/db.py", line 58, in _execute_wrapper
testbot-mysql      |     cur.execute(sql if self.type == self.SQLITE else sql.replace("?", "%s"), params)
testbot-mysql      |   File "/app/deps/mysql/connector/cursor_cext.py", line 330, in execute
testbot-mysql      |     result = self._cnx.cmd_query(
testbot-mysql      |              ^^^^^^^^^^^^^^^^^^^^
testbot-mysql      |   File "/app/deps/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
testbot-mysql      |     return method(cnx, *args, **kwargs)
testbot-mysql      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
testbot-mysql      |   File "/app/deps/mysql/connector/connection_cext.py", line 641, in cmd_query
testbot-mysql      |     raise get_mysql_exception(
testbot-mysql      | mysql.connector.errors.DatabaseError: 1364 (HY000): Field 'log_id' doesn't have a default value
testbot-mysql      |
testbot-mysql      | The above exception was the direct cause of the following exception:
testbot-mysql      |
testbot-mysql      | Traceback (most recent call last):
testbot-mysql      |   File "/app/core/command_service.py", line 207, in process_command
testbot-mysql      |     response = handler["callback"](CommandRequest(conn, channel, sender, reply), *self.process_matches(matches, handler["params"]))
testbot-mysql      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
testbot-mysql      |   File "/app/modules/standard/raid/raid_controller.py", line 236, in points_add_cmd
testbot-mysql      |     account = self.points_controller.get_account(raider.main_id, request.conn)
testbot-mysql      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
testbot-mysql      |   File "/app/modules/standard/raid/points_controller.py", line 242, in get_account
testbot-mysql      |     self.create_account(main_id, SenderObj(conn.get_char_id(),
testbot-mysql      |   File "/app/modules/standard/raid/points_controller.py", line 253, in create_account
testbot-mysql      |     self.add_log_entry(main_id, sender.char_id, "Account opened by %s" % sender.name)
testbot-mysql      |   File "/app/modules/standard/raid/points_controller.py", line 230, in add_log_entry
testbot-mysql      |     return self.db.exec(sql, [char_id, amount, leader_id, reason, int(time.time())])
testbot-mysql      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
testbot-mysql      |   File "/app/core/db.py", line 114, in exec
testbot-mysql      |     row_count, lastrowid = self._execute_wrapper(sql, params, map_result, log_query)
testbot-mysql      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
testbot-mysql      |   File "/app/core/db.py", line 62, in _execute_wrapper
testbot-mysql      |     raise SqlException("SQL Error: '%s' for '%s' [%s]" % (str(e), sql, ", ".join(map(lambda x: str(x), params)))) from e
testbot-mysql      | core.db.SqlException: SQL Error: '1364 (HY000): Field 'log_id' doesn't have a default value' for 'INSERT INTO points_log (char_id, audit, leader_id, reason, created_at) VALUES (?,?,?,?,?)' [1673852042, 0, 1673852370, Account opened by Captestslav2, 1706436652]
testbot-mysql      | 2024-01-28 10:10:52,024 - INFO - core.tyrbot - (bot0) To Capmafroob: There was an error processing your request.
```

**Comment by cap5lut** [comment]
as discussed in discord, the error is that the `log_id` should be `AUTOINCREMENT` [here](https://github.com/Budabot/Tyrbot/blob/master/modules/standard/raid/points_controller.py#L31).

im working on a fix now
