### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by cap5lut** [Budabot/Tyrbot#142]
I'm just relaying this from discord:
> Quick question im trying to run tybot on a fresh install of ubuntu 24 server i have python3 and pip install sqlite3 etc but when i try to run the bot im getting this error:
 ```
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
     File "/home/dev/aobots/bootstrap.py", line 8, in <module>     from upgrade import run_upgrades
     File "/home/dev/aobots/upgrade.py", line 1, in <module>     from core.db import DB
     File "/home/dev/aobots/core/db.py", line 4, in <module>     from pkg_resources import parse_version
```
the user is *not* using docker.

`pkg_resources` comes from `setuptools`, which seems to be not installed by default there, so adding it to `requirements.txt` might fix this.

**Comment by krynnotaur** [comment]
[pkg_resources is deprecated and removed in Python 3.12](https://github.com/mu-editor/mu/issues/2485)

**Comment by bigwheels16** [comment]
this should be fixed now
