### ISSUE TITLE
Fresh python install gives me syntax error in file "/home/pi/Tyrbot/core/text.py", line 13

### ISSUE THREAD

**Issue by jroovers** [Budabot/Tyrbot#21]
Traceback (most recent call last):
  File "bootstrap.py", line 36, in <module>
    Registry.load_instances(paths)
  File "/home/pi/Tyrbot/core/registry.py", line 84, in load_instances
    cls.load_module(file)
  File "/home/pi/Tyrbot/core/registry.py", line 90, in load_module
    importlib.import_module(file.replace("\\", ".").replace("/", "."))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/Tyrbot/core/text.py", line 13
    self.setting_service: SettingService = registry.get_instance("setting_service")
                        ^
SyntaxError: invalid syntax

https://github.com/Budabot/Tyrbot/blob/7a87ceb3dca9709845dc10c9732589170c767650/core/text.py#L13

on fresh python3 + pip install. 
Am I missing a dependency? I have tried modifying 
```self.setting_service: SettingService = registry.get_instance("setting_service")```
to
```self.setting_service = registry.get_instance("setting_service")```
which python accepts but these kind of assignments(I think?, I'm not familiar with python) are used on multiple locations in the code.

**Comment by Nepherius** [comment]
Assuming you're using start.sh, edit it and use python3.6 or higher:
`python3.6 bootstrap.py && exit`

**Comment by bigwheels16** [comment]
are you using python 3.6?  unfortunately, neither 3.5 or 3.7 or any other 3.x version will work currently

**Comment by jroovers** [comment]
Thank you both, I AM on an older version (Python3.5 on linux/arm) and I just tested on a 3.7 windows install and that seemed to work fine. Thanks for the quick replies.
